### ISSUE TITLE
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by rochelryu** [sub2u/vimeo-downloader#12]
this is message to return when the function vidl(url).pipe(fs.createWriteStream(input)) is lunch

**Comment by sub2u** [comment]
Can you please provide a video URL you are trying?

**Comment by peterAzv** [comment]
The sample URL 
https://vimeo.com/183482793

**Comment by sebgreen** [comment]
This does not work - generated file is empty.

**Comment by sub2u** [comment]
@sebgreen @peterAzv Try below code is working as expected I can able to download the package

`var fs = require('fs');
var vidl = require('..');

stream = vidl('https://vimeo.com/183482793', {quality: '360p'});

stream.pipe(fs.createWriteStream('./video.mp4'));

stream.on('data', function(chunk) {
  console.log('downloaded', chunk.length);
});

stream.on('end', function() {
  console.log('Finished');
});`
