### ISSUE TITLE
Unable to catch stream errors

### ISSUE THREAD

**Issue by bonaccorsop** [sub2u/vimeo-downloader#2]
I use this package at version ^1.0.3

I need to trap stream errors.
For example I have this error that I can't catch:

"ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

I have this code:

```
let stream = vidl(url, { quality: '360p', format: 'mp4' });

stream.on('error', (err) => {
    //I should catch the error here!!
    //It seems doesn't work
    console.error(err);    
});

stream.on('finish', () => {
    //Ok here, I launch my finish event.
});

stream.pipe(fs.createWriteStream(filename));
```

**Comment by sub2u** [comment]
upgrading to ^1.0.4 fixes the problem
