### ISSUE TITLE
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by DQvsRA** [sub2u/vimeo-downloader#8]
Thats what I get when trying to request video to download:

```
vidl('https://vimeo.com/183482793')
		.pipe(fs.createWriteStream('video.flv'));
```

**WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden**

**Comment by sub2u** [comment]
yes, we have warning but that won't effect anything about downloading the video right ?

**Comment by sub2u** [comment]
Since these are just warnings I am closing this issue.
